# NumPy

Read the link https://numpy.org/doc/stable/user/quickstart.html before starting the exercises. 

In [3]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [4]:
A = np.arange(1, 16).reshape(3,5)

In [5]:
print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)

2
(3, 5)
15
int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [6]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [7]:
print(B-C)
print()
print(B*C)
print()
print(B@C)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on matrix D:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [8]:
D = np.arange(1, 10).reshape(3, 3)
print(D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print(np.exp(D)) # Exponentiate each number elementwise (use the np.exp function).
print()
print(min(D.flatten())) # Find the minimum value in D (use the flatten method first).
print()
print(np.min(D, axis=1)) # Find the minimum value in each row (use the axis parameter of the np.minimum function).
print()
print(np.sum(D, axis=0)) # Find the sum of each column (use the axis parameter of the np.sum function).
print()

print(np.argmin(D)) # Find the index of the minimum value in D (use the np.argmin function).
print()
print(np.argmin(D, axis=1)) # Find the index of the minimum value in each row (use the axis parameter of the np.argmin function).
print()
print(np.sum(D)) # Find the sum of all elements in D (use the np.sum function).
print()
print(np.mean(D, axis=0)) # Find the mean of each column (use the axis parameter of the np.mean function).
print()
print(np.median(D, axis=0))
print()


[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

1

[1 4 7]

[12 15 18]

0

[0 0 0]

45

[4. 5. 6.]

[4. 5. 6.]



### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [10]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [11]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

The missing indices are implicitly replaced with : (take everything) for the remaining axes.<br>
So A[1] is equal to A[1, :], or A[1, ...]

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [12]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [13]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [14]:
for i in A.flatten():
    print(i)
    

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [15]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


a.reshape((2, 3, -1)) -> -1 means to automatically fill the number in this axes, to fit the shape for the total number of elements.<br>
In this case, (2, 3, -1) is equal to (2, 3, 5) since 30/2/3=5

### Broadcasting
Read the link https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting and the document *"matematik_yh_kap_10"* (solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh) before starting the exercises below.  

If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

##### Remark on Broadcasting when doing Linear Algebra calculations in Python. 
From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices.

In [16]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [17]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [18]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


### Vector and matrix algebra

Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.

Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).

In [19]:
def add_mult_matrices(A: np.ndarray, B: np.ndarray, Operation: str) -> np.ndarray:
    if Operation == "add":
        if A.shape != B.shape:
            raise ValueError("Matrices must have the same shape for addition")
        else:
            return A + B
    elif Operation == "multiply":
        if A.shape[1] != B.shape[0]:
            raise ValueError("Number of columns in A must equal number of rows in B for multiplication")
        return A * B
    else:
        raise ValueError("Unsupported operation")

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. Note, the function you created above can be used. 

Uppgift 10.1.1. Definiera vektorn x enligt nedan.

x = (4,3)

(a) Vilken dimension har vektorn x?

(b) Beräkna 5x.

(c) Beräkna 3x.

(d) Beräkna 5x + 3x.

(e) Beräkna 8x.

(f) Beräkna 4x - x.

(g) Beräkna xT, vilken blir den nya dimensionen efter att
transponeringen utförts?

(h) Ar x + x' definierat?

(i) Beräkna ⎜⎜x⎜⎜

In [20]:
x = np.array([4, 3])
print(x)
print(x.ndim) # (a)
print(x * 5) # (a)
print(x * 3) # (b)
print(x * 5 + x * 3) # (c)
print(x * 8) # (d)
print(x * 4 - x * 1) # (e)
y = x.T
print(y) # (f)
print(y.ndim) # (g)
print(x + y) # (h)
print(np.linalg.norm(x)) # (i)

[4 3]
1
[20 15]
[12  9]
[32 24]
[32 24]
[12  9]
[4 3]
1
[8 6]
5.0


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

Uppgift 10.2.1. Definiera matriserna:
<p align="left">
  <img src="./Image_matrices.png" width=50%;>
</p>
Om det är definierat, utför följande beräkningar:

(a) 2A

(b) B-2A

(c) 3C -2E

(d) 2D - 3C



In [21]:
A = np.array([[2, 1, -1], [1, -1, 1]])
print(f'A =\n{A}')
print()

B = np.array([[4, -2, 1], [2, -4, -2]])
print(f'B =\n{B}')
print()

C = np.array([[1, 2], [2, 1]])
print(f'C =\n{C}')
print()

D = np.array([[3, 4], [4, 3]])
print(f'D =\n{D}')
print()

E =np.array([1, 2])
print(f'E =\n{E}')
print()

I = np.array([[1, 0], [0, 1]])
print(f'I =\n{I}')
print()

print(f'2A=\n{A * 2}') # (a)
print()

print(f'B - 2A=\n{B - A * 2}') # (b)
print()

print(f'3C - 2E=\n{3*C - 2*E.reshape(2,1)}') # (c)
print()

print(f'2D - 3C=\n{2*D - 3*C}') # (d)
print()



A =
[[ 2  1 -1]
 [ 1 -1  1]]

B =
[[ 4 -2  1]
 [ 2 -4 -2]]

C =
[[1 2]
 [2 1]]

D =
[[3 4]
 [4 3]]

E =
[1 2]

I =
[[1 0]
 [0 1]]

2A=
[[ 4  2 -2]
 [ 2 -2  2]]

B - 2A=
[[ 0 -4  3]
 [ 0 -2 -4]]

3C - 2E=
[[ 1  4]
 [ 2 -1]]

2D - 3C=
[[3 2]
 [2 3]]



(e) DT + 2D

(f) 2CT —2DT

(g) AT - B

(h) AC

(i) CD

(j) CB

(k) CI

(1) AB<sup>T</sup>

In [22]:
print(f'D.T + 2D=\n{D.T + 2*D}') # (e)
print()

print(f'2C.T - 2D.T=\n{2*C.T - 2*D.T}') # (f)
print()

print(f'2C.T - 2D.T=\n{2*C.T - 2*D.T}') # (f)
print()

#print(f'A.T - B=\n{A.T - B}') # (g) -> This operation is not defined due to shape mismatch.
print()

#print(f'AC=\n{A @ C}') # (h) -> This operation is not defined due to shape mismatch.
print()

print(f'CD =\n{C @ D}') # (i)
print()

#print(f'CB =\n{C @ B.T}') # (j) -> This operation is not defined due to shape mismatch.
print()

print(f'CI =\n{C @ I}') # (k)
print()

print(f'AB.T =\n{A @ B.T}') # (l)
print()


D.T + 2D=
[[ 9 12]
 [12  9]]

2C.T - 2D.T=
[[-4 -4]
 [-4 -4]]

2C.T - 2D.T=
[[-4 -4]
 [-4 -4]]



CD =
[[11 10]
 [10 11]]


CI =
[[1 2]
 [2 1]]

AB.T =
[[5 2]
 [7 4]]



<p align="left">
  <img src="./Uppgift_10_2_2_2.png" width=50%;>
</p>

In [23]:
A = np.array([[2, 3, 4], [5, 4, 1]])
print(f'AA.T =\n{A @ A.T}')
print()


AA.T =
[[29 26]
 [26 42]]



<p align="left">
  <img src="./Uppgift_10_2_3.png" width=50%;>
</p>

In [24]:
A = np.array([[1, 2], [2, 4]])
print(f'A =\n{A }')
print()

B = np.array([[2, 1], [1, 3]])
print(f'B =\n{B }')
print()

C = np.array([[4, 3], [0, 2]])
print(f'C =\n{C }')
print()

print('AB = AC? ', np.array_equal(A @ B, A @ C))
print()


print(f'B is qual to C? ', np.array_equal(B, C))
print()

A =
[[1 2]
 [2 4]]

B =
[[2 1]
 [1 3]]

C =
[[4 3]
 [0 2]]

AB = AC?  True

B is qual to C?  False



### Copies and Views
Read the link https://numpy.org/doc/stable/user/basics.copies.html before starting the exercises below. 

Basic indexing creates a view. How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?

In [25]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [28]:
print(f'v2.base is v1? ', v2.base is v1)
print()

v2[-1] = 123
print(v1) # Should reflect the change, since v2 is a view of v1
print(v2)


v2.base is v1?  True

[  0   1   2 123]
[  2 123]
